/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as TeacherSurveyRouteRouteImport } from './routes/teacher/survey/route'
import { Route as TeacherRegisterRouteRouteImport } from './routes/teacher/register/route'
import { Route as TeacherOtpRouteRouteImport } from './routes/teacher/otp/route'
import { Route as TeacherLoginRouteRouteImport } from './routes/teacher/login/route'
import { Route as TeacherAuthenticatedRouteRouteImport } from './routes/teacher/_authenticated/route'
import { Route as LandingContactRouteRouteImport } from './routes/_landing/contact/route'
import { Route as LandingIndexRouteRouteImport } from './routes/_landing/index/route'
import { Route as TeacherAuthenticatedCoursesRouteRouteImport } from './routes/teacher/_authenticated/courses/route'
import { Route as TeacherAuthenticatedCoursesNewRouteRouteImport } from './routes/teacher/_authenticated/courses/new/route'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSurveyRouteRoute = TeacherSurveyRouteRouteImport.update({
  id: '/teacher/survey',
  path: '/teacher/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRegisterRouteRoute = TeacherRegisterRouteRouteImport.update({
  id: '/teacher/register',
  path: '/teacher/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherOtpRouteRoute = TeacherOtpRouteRouteImport.update({
  id: '/teacher/otp',
  path: '/teacher/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRouteRoute = TeacherLoginRouteRouteImport.update({
  id: '/teacher/login',
  path: '/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAuthenticatedRouteRoute =
  TeacherAuthenticatedRouteRouteImport.update({
    id: '/teacher/_authenticated',
    path: '/teacher',
    getParentRoute: () => rootRouteImport,
  } as any)
const LandingContactRouteRoute = LandingContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingIndexRouteRoute = LandingIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => LandingRouteRoute,
} as any)
const TeacherAuthenticatedCoursesRouteRoute =
  TeacherAuthenticatedCoursesRouteRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedCoursesNewRouteRoute =
  TeacherAuthenticatedCoursesNewRouteRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TeacherAuthenticatedCoursesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/test': typeof TestRouteRoute
  '/contact': typeof LandingContactRouteRoute
  '/teacher': typeof TeacherAuthenticatedRouteRouteWithChildren
  '/teacher/login': typeof TeacherLoginRouteRoute
  '/teacher/otp': typeof TeacherOtpRouteRoute
  '/teacher/register': typeof TeacherRegisterRouteRoute
  '/teacher/survey': typeof TeacherSurveyRouteRoute
  '/teacher/courses': typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
  '/teacher/courses/new': typeof TeacherAuthenticatedCoursesNewRouteRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRouteRoute
  '/contact': typeof LandingContactRouteRoute
  '/teacher': typeof TeacherAuthenticatedRouteRouteWithChildren
  '/teacher/login': typeof TeacherLoginRouteRoute
  '/teacher/otp': typeof TeacherOtpRouteRoute
  '/teacher/register': typeof TeacherRegisterRouteRoute
  '/teacher/survey': typeof TeacherSurveyRouteRoute
  '/teacher/courses': typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
  '/teacher/courses/new': typeof TeacherAuthenticatedCoursesNewRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteRouteWithChildren
  '/test': typeof TestRouteRoute
  '/_landing/': typeof LandingIndexRouteRoute
  '/_landing/contact': typeof LandingContactRouteRoute
  '/teacher/_authenticated': typeof TeacherAuthenticatedRouteRouteWithChildren
  '/teacher/login': typeof TeacherLoginRouteRoute
  '/teacher/otp': typeof TeacherOtpRouteRoute
  '/teacher/register': typeof TeacherRegisterRouteRoute
  '/teacher/survey': typeof TeacherSurveyRouteRoute
  '/teacher/_authenticated/courses': typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
  '/teacher/_authenticated/courses/new': typeof TeacherAuthenticatedCoursesNewRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/test'
    | '/contact'
    | '/teacher'
    | '/teacher/login'
    | '/teacher/otp'
    | '/teacher/register'
    | '/teacher/survey'
    | '/teacher/courses'
    | '/teacher/courses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/contact'
    | '/teacher'
    | '/teacher/login'
    | '/teacher/otp'
    | '/teacher/register'
    | '/teacher/survey'
    | '/teacher/courses'
    | '/teacher/courses/new'
  id:
    | '__root__'
    | '/_landing'
    | '/test'
    | '/_landing/'
    | '/_landing/contact'
    | '/teacher/_authenticated'
    | '/teacher/login'
    | '/teacher/otp'
    | '/teacher/register'
    | '/teacher/survey'
    | '/teacher/_authenticated/courses'
    | '/teacher/_authenticated/courses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  TestRouteRoute: typeof TestRouteRoute
  TeacherAuthenticatedRouteRoute: typeof TeacherAuthenticatedRouteRouteWithChildren
  TeacherLoginRouteRoute: typeof TeacherLoginRouteRoute
  TeacherOtpRouteRoute: typeof TeacherOtpRouteRoute
  TeacherRegisterRouteRoute: typeof TeacherRegisterRouteRoute
  TeacherSurveyRouteRoute: typeof TeacherSurveyRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/survey': {
      id: '/teacher/survey'
      path: '/teacher/survey'
      fullPath: '/teacher/survey'
      preLoaderRoute: typeof TeacherSurveyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/register': {
      id: '/teacher/register'
      path: '/teacher/register'
      fullPath: '/teacher/register'
      preLoaderRoute: typeof TeacherRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/otp': {
      id: '/teacher/otp'
      path: '/teacher/otp'
      fullPath: '/teacher/otp'
      preLoaderRoute: typeof TeacherOtpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/login': {
      id: '/teacher/login'
      path: '/teacher/login'
      fullPath: '/teacher/login'
      preLoaderRoute: typeof TeacherLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/_authenticated': {
      id: '/teacher/_authenticated'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactRouteRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingIndexRouteRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/teacher/_authenticated/courses': {
      id: '/teacher/_authenticated/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherAuthenticatedCoursesRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/courses/new': {
      id: '/teacher/_authenticated/courses/new'
      path: '/new'
      fullPath: '/teacher/courses/new'
      preLoaderRoute: typeof TeacherAuthenticatedCoursesNewRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedCoursesRouteRoute
    }
  }
}

interface LandingRouteRouteChildren {
  LandingIndexRouteRoute: typeof LandingIndexRouteRoute
  LandingContactRouteRoute: typeof LandingContactRouteRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexRouteRoute: LandingIndexRouteRoute,
  LandingContactRouteRoute: LandingContactRouteRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface TeacherAuthenticatedCoursesRouteRouteChildren {
  TeacherAuthenticatedCoursesNewRouteRoute: typeof TeacherAuthenticatedCoursesNewRouteRoute
}

const TeacherAuthenticatedCoursesRouteRouteChildren: TeacherAuthenticatedCoursesRouteRouteChildren =
  {
    TeacherAuthenticatedCoursesNewRouteRoute:
      TeacherAuthenticatedCoursesNewRouteRoute,
  }

const TeacherAuthenticatedCoursesRouteRouteWithChildren =
  TeacherAuthenticatedCoursesRouteRoute._addFileChildren(
    TeacherAuthenticatedCoursesRouteRouteChildren,
  )

interface TeacherAuthenticatedRouteRouteChildren {
  TeacherAuthenticatedCoursesRouteRoute: typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
}

const TeacherAuthenticatedRouteRouteChildren: TeacherAuthenticatedRouteRouteChildren =
  {
    TeacherAuthenticatedCoursesRouteRoute:
      TeacherAuthenticatedCoursesRouteRouteWithChildren,
  }

const TeacherAuthenticatedRouteRouteWithChildren =
  TeacherAuthenticatedRouteRoute._addFileChildren(
    TeacherAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LandingRouteRoute: LandingRouteRouteWithChildren,
  TestRouteRoute: TestRouteRoute,
  TeacherAuthenticatedRouteRoute: TeacherAuthenticatedRouteRouteWithChildren,
  TeacherLoginRouteRoute: TeacherLoginRouteRoute,
  TeacherOtpRouteRoute: TeacherOtpRouteRoute,
  TeacherRegisterRouteRoute: TeacherRegisterRouteRoute,
  TeacherSurveyRouteRoute: TeacherSurveyRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
