/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as TeacherSurveyRouteRouteImport } from './routes/teacher/survey/route'
import { Route as TeacherReuploadRouteRouteImport } from './routes/teacher/reupload/route'
import { Route as TeacherRegisterRouteRouteImport } from './routes/teacher/register/route'
import { Route as TeacherLoginRouteRouteImport } from './routes/teacher/login/route'
import { Route as TeacherAwaitRouteRouteImport } from './routes/teacher/await/route'
import { Route as TeacherAuthenticatedRouteRouteImport } from './routes/teacher/_authenticated/route'
import { Route as LandingContactRouteRouteImport } from './routes/_landing/contact/route'
import { Route as LandingIndexRouteRouteImport } from './routes/_landing/index/route'
import { Route as TeacherAuthenticatedSessionsRouteRouteImport } from './routes/teacher/_authenticated/sessions/route'
import { Route as TeacherAuthenticatedRequestsRouteRouteImport } from './routes/teacher/_authenticated/requests/route'
import { Route as TeacherAuthenticatedProfileRouteRouteImport } from './routes/teacher/_authenticated/profile/route'
import { Route as TeacherAuthenticatedNotificationsRouteRouteImport } from './routes/teacher/_authenticated/notifications/route'
import { Route as TeacherAuthenticatedFinanceRouteRouteImport } from './routes/teacher/_authenticated/finance/route'
import { Route as TeacherAuthenticatedDashboardRouteRouteImport } from './routes/teacher/_authenticated/dashboard/route'
import { Route as TeacherAuthenticatedCoursesRouteRouteImport } from './routes/teacher/_authenticated/courses/route'
import { Route as TeacherAuthenticatedContentRouteRouteImport } from './routes/teacher/_authenticated/content/route'
import { Route as TeacherAuthenticatedCalendarRouteRouteImport } from './routes/teacher/_authenticated/calendar/route'
import { Route as TeacherAuthenticatedIndexRouteRouteImport } from './routes/teacher/_authenticated/index/route'
import { Route as TeacherAuthenticatedSessionsSessionIdRouteRouteImport } from './routes/teacher/_authenticated/sessions/$sessionId/route'
import { Route as TeacherAuthenticatedRequestsRequestIdRouteRouteImport } from './routes/teacher/_authenticated/requests/$requestId/route'
import { Route as TeacherAuthenticatedCoursesNewRouteRouteImport } from './routes/teacher/_authenticated/courses/new/route'
import { Route as TeacherAuthenticatedCoursesCourseIdRouteRouteImport } from './routes/teacher/_authenticated/courses/$courseId/route'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSurveyRouteRoute = TeacherSurveyRouteRouteImport.update({
  id: '/teacher/survey',
  path: '/teacher/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReuploadRouteRoute = TeacherReuploadRouteRouteImport.update({
  id: '/teacher/reupload',
  path: '/teacher/reupload',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRegisterRouteRoute = TeacherRegisterRouteRouteImport.update({
  id: '/teacher/register',
  path: '/teacher/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRouteRoute = TeacherLoginRouteRouteImport.update({
  id: '/teacher/login',
  path: '/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAwaitRouteRoute = TeacherAwaitRouteRouteImport.update({
  id: '/teacher/await',
  path: '/teacher/await',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAuthenticatedRouteRoute =
  TeacherAuthenticatedRouteRouteImport.update({
    id: '/teacher/_authenticated',
    path: '/teacher',
    getParentRoute: () => rootRouteImport,
  } as any)
const LandingContactRouteRoute = LandingContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingIndexRouteRoute = LandingIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => LandingRouteRoute,
} as any)
const TeacherAuthenticatedSessionsRouteRoute =
  TeacherAuthenticatedSessionsRouteRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedRequestsRouteRoute =
  TeacherAuthenticatedRequestsRouteRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedProfileRouteRoute =
  TeacherAuthenticatedProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedNotificationsRouteRoute =
  TeacherAuthenticatedNotificationsRouteRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedFinanceRouteRoute =
  TeacherAuthenticatedFinanceRouteRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedDashboardRouteRoute =
  TeacherAuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedCoursesRouteRoute =
  TeacherAuthenticatedCoursesRouteRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedContentRouteRoute =
  TeacherAuthenticatedContentRouteRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedCalendarRouteRoute =
  TeacherAuthenticatedCalendarRouteRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedIndexRouteRoute =
  TeacherAuthenticatedIndexRouteRouteImport.update({
    id: '/',
    path: '',
    getParentRoute: () => TeacherAuthenticatedRouteRoute,
  } as any)
const TeacherAuthenticatedSessionsSessionIdRouteRoute =
  TeacherAuthenticatedSessionsSessionIdRouteRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => TeacherAuthenticatedSessionsRouteRoute,
  } as any)
const TeacherAuthenticatedRequestsRequestIdRouteRoute =
  TeacherAuthenticatedRequestsRequestIdRouteRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => TeacherAuthenticatedRequestsRouteRoute,
  } as any)
const TeacherAuthenticatedCoursesNewRouteRoute =
  TeacherAuthenticatedCoursesNewRouteRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TeacherAuthenticatedCoursesRouteRoute,
  } as any)
const TeacherAuthenticatedCoursesCourseIdRouteRoute =
  TeacherAuthenticatedCoursesCourseIdRouteRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => TeacherAuthenticatedCoursesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/test': typeof TestRouteRoute
  '/contact': typeof LandingContactRouteRoute
  '/teacher': typeof TeacherAuthenticatedIndexRouteRoute
  '/teacher/await': typeof TeacherAwaitRouteRoute
  '/teacher/login': typeof TeacherLoginRouteRoute
  '/teacher/register': typeof TeacherRegisterRouteRoute
  '/teacher/reupload': typeof TeacherReuploadRouteRoute
  '/teacher/survey': typeof TeacherSurveyRouteRoute
  '/teacher/calendar': typeof TeacherAuthenticatedCalendarRouteRoute
  '/teacher/content': typeof TeacherAuthenticatedContentRouteRoute
  '/teacher/courses': typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
  '/teacher/dashboard': typeof TeacherAuthenticatedDashboardRouteRoute
  '/teacher/finance': typeof TeacherAuthenticatedFinanceRouteRoute
  '/teacher/notifications': typeof TeacherAuthenticatedNotificationsRouteRoute
  '/teacher/profile': typeof TeacherAuthenticatedProfileRouteRoute
  '/teacher/requests': typeof TeacherAuthenticatedRequestsRouteRouteWithChildren
  '/teacher/sessions': typeof TeacherAuthenticatedSessionsRouteRouteWithChildren
  '/teacher/courses/$courseId': typeof TeacherAuthenticatedCoursesCourseIdRouteRoute
  '/teacher/courses/new': typeof TeacherAuthenticatedCoursesNewRouteRoute
  '/teacher/requests/$requestId': typeof TeacherAuthenticatedRequestsRequestIdRouteRoute
  '/teacher/sessions/$sessionId': typeof TeacherAuthenticatedSessionsSessionIdRouteRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRouteRoute
  '/contact': typeof LandingContactRouteRoute
  '/teacher': typeof TeacherAuthenticatedIndexRouteRoute
  '/teacher/await': typeof TeacherAwaitRouteRoute
  '/teacher/login': typeof TeacherLoginRouteRoute
  '/teacher/register': typeof TeacherRegisterRouteRoute
  '/teacher/reupload': typeof TeacherReuploadRouteRoute
  '/teacher/survey': typeof TeacherSurveyRouteRoute
  '/teacher/calendar': typeof TeacherAuthenticatedCalendarRouteRoute
  '/teacher/content': typeof TeacherAuthenticatedContentRouteRoute
  '/teacher/courses': typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
  '/teacher/dashboard': typeof TeacherAuthenticatedDashboardRouteRoute
  '/teacher/finance': typeof TeacherAuthenticatedFinanceRouteRoute
  '/teacher/notifications': typeof TeacherAuthenticatedNotificationsRouteRoute
  '/teacher/profile': typeof TeacherAuthenticatedProfileRouteRoute
  '/teacher/requests': typeof TeacherAuthenticatedRequestsRouteRouteWithChildren
  '/teacher/sessions': typeof TeacherAuthenticatedSessionsRouteRouteWithChildren
  '/teacher/courses/$courseId': typeof TeacherAuthenticatedCoursesCourseIdRouteRoute
  '/teacher/courses/new': typeof TeacherAuthenticatedCoursesNewRouteRoute
  '/teacher/requests/$requestId': typeof TeacherAuthenticatedRequestsRequestIdRouteRoute
  '/teacher/sessions/$sessionId': typeof TeacherAuthenticatedSessionsSessionIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteRouteWithChildren
  '/test': typeof TestRouteRoute
  '/_landing/': typeof LandingIndexRouteRoute
  '/_landing/contact': typeof LandingContactRouteRoute
  '/teacher/_authenticated': typeof TeacherAuthenticatedRouteRouteWithChildren
  '/teacher/await': typeof TeacherAwaitRouteRoute
  '/teacher/login': typeof TeacherLoginRouteRoute
  '/teacher/register': typeof TeacherRegisterRouteRoute
  '/teacher/reupload': typeof TeacherReuploadRouteRoute
  '/teacher/survey': typeof TeacherSurveyRouteRoute
  '/teacher/_authenticated/': typeof TeacherAuthenticatedIndexRouteRoute
  '/teacher/_authenticated/calendar': typeof TeacherAuthenticatedCalendarRouteRoute
  '/teacher/_authenticated/content': typeof TeacherAuthenticatedContentRouteRoute
  '/teacher/_authenticated/courses': typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
  '/teacher/_authenticated/dashboard': typeof TeacherAuthenticatedDashboardRouteRoute
  '/teacher/_authenticated/finance': typeof TeacherAuthenticatedFinanceRouteRoute
  '/teacher/_authenticated/notifications': typeof TeacherAuthenticatedNotificationsRouteRoute
  '/teacher/_authenticated/profile': typeof TeacherAuthenticatedProfileRouteRoute
  '/teacher/_authenticated/requests': typeof TeacherAuthenticatedRequestsRouteRouteWithChildren
  '/teacher/_authenticated/sessions': typeof TeacherAuthenticatedSessionsRouteRouteWithChildren
  '/teacher/_authenticated/courses/$courseId': typeof TeacherAuthenticatedCoursesCourseIdRouteRoute
  '/teacher/_authenticated/courses/new': typeof TeacherAuthenticatedCoursesNewRouteRoute
  '/teacher/_authenticated/requests/$requestId': typeof TeacherAuthenticatedRequestsRequestIdRouteRoute
  '/teacher/_authenticated/sessions/$sessionId': typeof TeacherAuthenticatedSessionsSessionIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/test'
    | '/contact'
    | '/teacher'
    | '/teacher/await'
    | '/teacher/login'
    | '/teacher/register'
    | '/teacher/reupload'
    | '/teacher/survey'
    | '/teacher/calendar'
    | '/teacher/content'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/finance'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/requests'
    | '/teacher/sessions'
    | '/teacher/courses/$courseId'
    | '/teacher/courses/new'
    | '/teacher/requests/$requestId'
    | '/teacher/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/contact'
    | '/teacher'
    | '/teacher/await'
    | '/teacher/login'
    | '/teacher/register'
    | '/teacher/reupload'
    | '/teacher/survey'
    | '/teacher/calendar'
    | '/teacher/content'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/finance'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/requests'
    | '/teacher/sessions'
    | '/teacher/courses/$courseId'
    | '/teacher/courses/new'
    | '/teacher/requests/$requestId'
    | '/teacher/sessions/$sessionId'
  id:
    | '__root__'
    | '/_landing'
    | '/test'
    | '/_landing/'
    | '/_landing/contact'
    | '/teacher/_authenticated'
    | '/teacher/await'
    | '/teacher/login'
    | '/teacher/register'
    | '/teacher/reupload'
    | '/teacher/survey'
    | '/teacher/_authenticated/'
    | '/teacher/_authenticated/calendar'
    | '/teacher/_authenticated/content'
    | '/teacher/_authenticated/courses'
    | '/teacher/_authenticated/dashboard'
    | '/teacher/_authenticated/finance'
    | '/teacher/_authenticated/notifications'
    | '/teacher/_authenticated/profile'
    | '/teacher/_authenticated/requests'
    | '/teacher/_authenticated/sessions'
    | '/teacher/_authenticated/courses/$courseId'
    | '/teacher/_authenticated/courses/new'
    | '/teacher/_authenticated/requests/$requestId'
    | '/teacher/_authenticated/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  TestRouteRoute: typeof TestRouteRoute
  TeacherAuthenticatedRouteRoute: typeof TeacherAuthenticatedRouteRouteWithChildren
  TeacherAwaitRouteRoute: typeof TeacherAwaitRouteRoute
  TeacherLoginRouteRoute: typeof TeacherLoginRouteRoute
  TeacherRegisterRouteRoute: typeof TeacherRegisterRouteRoute
  TeacherReuploadRouteRoute: typeof TeacherReuploadRouteRoute
  TeacherSurveyRouteRoute: typeof TeacherSurveyRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/survey': {
      id: '/teacher/survey'
      path: '/teacher/survey'
      fullPath: '/teacher/survey'
      preLoaderRoute: typeof TeacherSurveyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reupload': {
      id: '/teacher/reupload'
      path: '/teacher/reupload'
      fullPath: '/teacher/reupload'
      preLoaderRoute: typeof TeacherReuploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/register': {
      id: '/teacher/register'
      path: '/teacher/register'
      fullPath: '/teacher/register'
      preLoaderRoute: typeof TeacherRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/login': {
      id: '/teacher/login'
      path: '/teacher/login'
      fullPath: '/teacher/login'
      preLoaderRoute: typeof TeacherLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/await': {
      id: '/teacher/await'
      path: '/teacher/await'
      fullPath: '/teacher/await'
      preLoaderRoute: typeof TeacherAwaitRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/_authenticated': {
      id: '/teacher/_authenticated'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactRouteRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingIndexRouteRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/teacher/_authenticated/sessions': {
      id: '/teacher/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/teacher/sessions'
      preLoaderRoute: typeof TeacherAuthenticatedSessionsRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/requests': {
      id: '/teacher/_authenticated/requests'
      path: '/requests'
      fullPath: '/teacher/requests'
      preLoaderRoute: typeof TeacherAuthenticatedRequestsRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/profile': {
      id: '/teacher/_authenticated/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherAuthenticatedProfileRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/notifications': {
      id: '/teacher/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherAuthenticatedNotificationsRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/finance': {
      id: '/teacher/_authenticated/finance'
      path: '/finance'
      fullPath: '/teacher/finance'
      preLoaderRoute: typeof TeacherAuthenticatedFinanceRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/dashboard': {
      id: '/teacher/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherAuthenticatedDashboardRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/courses': {
      id: '/teacher/_authenticated/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherAuthenticatedCoursesRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/content': {
      id: '/teacher/_authenticated/content'
      path: '/content'
      fullPath: '/teacher/content'
      preLoaderRoute: typeof TeacherAuthenticatedContentRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/calendar': {
      id: '/teacher/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherAuthenticatedCalendarRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/': {
      id: '/teacher/_authenticated/'
      path: ''
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherAuthenticatedIndexRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRouteRoute
    }
    '/teacher/_authenticated/sessions/$sessionId': {
      id: '/teacher/_authenticated/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/teacher/sessions/$sessionId'
      preLoaderRoute: typeof TeacherAuthenticatedSessionsSessionIdRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedSessionsRouteRoute
    }
    '/teacher/_authenticated/requests/$requestId': {
      id: '/teacher/_authenticated/requests/$requestId'
      path: '/$requestId'
      fullPath: '/teacher/requests/$requestId'
      preLoaderRoute: typeof TeacherAuthenticatedRequestsRequestIdRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedRequestsRouteRoute
    }
    '/teacher/_authenticated/courses/new': {
      id: '/teacher/_authenticated/courses/new'
      path: '/new'
      fullPath: '/teacher/courses/new'
      preLoaderRoute: typeof TeacherAuthenticatedCoursesNewRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedCoursesRouteRoute
    }
    '/teacher/_authenticated/courses/$courseId': {
      id: '/teacher/_authenticated/courses/$courseId'
      path: '/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof TeacherAuthenticatedCoursesCourseIdRouteRouteImport
      parentRoute: typeof TeacherAuthenticatedCoursesRouteRoute
    }
  }
}

interface LandingRouteRouteChildren {
  LandingIndexRouteRoute: typeof LandingIndexRouteRoute
  LandingContactRouteRoute: typeof LandingContactRouteRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexRouteRoute: LandingIndexRouteRoute,
  LandingContactRouteRoute: LandingContactRouteRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface TeacherAuthenticatedCoursesRouteRouteChildren {
  TeacherAuthenticatedCoursesCourseIdRouteRoute: typeof TeacherAuthenticatedCoursesCourseIdRouteRoute
  TeacherAuthenticatedCoursesNewRouteRoute: typeof TeacherAuthenticatedCoursesNewRouteRoute
}

const TeacherAuthenticatedCoursesRouteRouteChildren: TeacherAuthenticatedCoursesRouteRouteChildren =
  {
    TeacherAuthenticatedCoursesCourseIdRouteRoute:
      TeacherAuthenticatedCoursesCourseIdRouteRoute,
    TeacherAuthenticatedCoursesNewRouteRoute:
      TeacherAuthenticatedCoursesNewRouteRoute,
  }

const TeacherAuthenticatedCoursesRouteRouteWithChildren =
  TeacherAuthenticatedCoursesRouteRoute._addFileChildren(
    TeacherAuthenticatedCoursesRouteRouteChildren,
  )

interface TeacherAuthenticatedRequestsRouteRouteChildren {
  TeacherAuthenticatedRequestsRequestIdRouteRoute: typeof TeacherAuthenticatedRequestsRequestIdRouteRoute
}

const TeacherAuthenticatedRequestsRouteRouteChildren: TeacherAuthenticatedRequestsRouteRouteChildren =
  {
    TeacherAuthenticatedRequestsRequestIdRouteRoute:
      TeacherAuthenticatedRequestsRequestIdRouteRoute,
  }

const TeacherAuthenticatedRequestsRouteRouteWithChildren =
  TeacherAuthenticatedRequestsRouteRoute._addFileChildren(
    TeacherAuthenticatedRequestsRouteRouteChildren,
  )

interface TeacherAuthenticatedSessionsRouteRouteChildren {
  TeacherAuthenticatedSessionsSessionIdRouteRoute: typeof TeacherAuthenticatedSessionsSessionIdRouteRoute
}

const TeacherAuthenticatedSessionsRouteRouteChildren: TeacherAuthenticatedSessionsRouteRouteChildren =
  {
    TeacherAuthenticatedSessionsSessionIdRouteRoute:
      TeacherAuthenticatedSessionsSessionIdRouteRoute,
  }

const TeacherAuthenticatedSessionsRouteRouteWithChildren =
  TeacherAuthenticatedSessionsRouteRoute._addFileChildren(
    TeacherAuthenticatedSessionsRouteRouteChildren,
  )

interface TeacherAuthenticatedRouteRouteChildren {
  TeacherAuthenticatedIndexRouteRoute: typeof TeacherAuthenticatedIndexRouteRoute
  TeacherAuthenticatedCalendarRouteRoute: typeof TeacherAuthenticatedCalendarRouteRoute
  TeacherAuthenticatedContentRouteRoute: typeof TeacherAuthenticatedContentRouteRoute
  TeacherAuthenticatedCoursesRouteRoute: typeof TeacherAuthenticatedCoursesRouteRouteWithChildren
  TeacherAuthenticatedDashboardRouteRoute: typeof TeacherAuthenticatedDashboardRouteRoute
  TeacherAuthenticatedFinanceRouteRoute: typeof TeacherAuthenticatedFinanceRouteRoute
  TeacherAuthenticatedNotificationsRouteRoute: typeof TeacherAuthenticatedNotificationsRouteRoute
  TeacherAuthenticatedProfileRouteRoute: typeof TeacherAuthenticatedProfileRouteRoute
  TeacherAuthenticatedRequestsRouteRoute: typeof TeacherAuthenticatedRequestsRouteRouteWithChildren
  TeacherAuthenticatedSessionsRouteRoute: typeof TeacherAuthenticatedSessionsRouteRouteWithChildren
}

const TeacherAuthenticatedRouteRouteChildren: TeacherAuthenticatedRouteRouteChildren =
  {
    TeacherAuthenticatedIndexRouteRoute: TeacherAuthenticatedIndexRouteRoute,
    TeacherAuthenticatedCalendarRouteRoute:
      TeacherAuthenticatedCalendarRouteRoute,
    TeacherAuthenticatedContentRouteRoute:
      TeacherAuthenticatedContentRouteRoute,
    TeacherAuthenticatedCoursesRouteRoute:
      TeacherAuthenticatedCoursesRouteRouteWithChildren,
    TeacherAuthenticatedDashboardRouteRoute:
      TeacherAuthenticatedDashboardRouteRoute,
    TeacherAuthenticatedFinanceRouteRoute:
      TeacherAuthenticatedFinanceRouteRoute,
    TeacherAuthenticatedNotificationsRouteRoute:
      TeacherAuthenticatedNotificationsRouteRoute,
    TeacherAuthenticatedProfileRouteRoute:
      TeacherAuthenticatedProfileRouteRoute,
    TeacherAuthenticatedRequestsRouteRoute:
      TeacherAuthenticatedRequestsRouteRouteWithChildren,
    TeacherAuthenticatedSessionsRouteRoute:
      TeacherAuthenticatedSessionsRouteRouteWithChildren,
  }

const TeacherAuthenticatedRouteRouteWithChildren =
  TeacherAuthenticatedRouteRoute._addFileChildren(
    TeacherAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LandingRouteRoute: LandingRouteRouteWithChildren,
  TestRouteRoute: TestRouteRoute,
  TeacherAuthenticatedRouteRoute: TeacherAuthenticatedRouteRouteWithChildren,
  TeacherAwaitRouteRoute: TeacherAwaitRouteRoute,
  TeacherLoginRouteRoute: TeacherLoginRouteRoute,
  TeacherRegisterRouteRoute: TeacherRegisterRouteRoute,
  TeacherReuploadRouteRoute: TeacherReuploadRouteRoute,
  TeacherSurveyRouteRoute: TeacherSurveyRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
